---
# tasks file for phill93.clusterhat
    - name: Installing required software
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        "{{ clusterhat_required_packages }}"

    - name: Installing Commandline Utility for the Clusterhat
      become: true
      get_url:
        url: "{{ clusterhat_cli_url }}"
        dest: "/sbin/clusterhat"
        mode: 0755
        owner: root
        group: root

    - name: Installing GUI Utility for the Clusterhat
      become: true
      get_url:
        url: "{{ clusterhat_gui_url }}"
        dest: "/sbin/clusterhat"
        mode: 0755
        owner: root
        group: root
      when: clusterhat_gui

    - name: Disable APIPA addresses
      become: true
      lineinfile:
        path: /etc/dhcpcd.conf
        line: "denyinterfaces eth0 ethpi1 ethpi2 ethpi3 ethpi4"
        state: present

    - name: Automatic Clusterhat init at Boot
      become: true
      lineinfile:
        path: /etc/rc.local
        insertbefore: "^exit 0"
        line: "/sbin/clusterhat init"
        state: present

    - name: Enable UART
      become: true
      lineinfile:
        path: /boot/config.txt
        regexp: "^#enable_uart="
        line: "enable_uart=1"
        state: present
      notify: reboot

    - name: Enable I2C
      block:
        - name: Enable I2C - Patching /boot/config.txt
          lineinfile:
            path: /boot/config.txt
            regexp: "^#dtparam=i2c_arm"
            line: "dtparam=i2c_arm"
          notify: reboot
          become: true

        - name: Enable I2C - Patching /etc/modules
          lineinfile:
            path: /etc/modules
            line: "i2c-dev"
            state: present
          notify: reboot
          become: true

    - name: Installing network configuration
      block:
        - name: Installing network configuration - /etc/network/interfaces.d/clusterhat
          get_url:
            url: "{{ clusterhat_network_cfg_url }}"
            dest: /etc/network/interfaces.d/clusterhat
            mode: 0644
            owner: root
            group: root
          become: true

        - name: Installing network configuration - /etc/network/interfaces.d/bridge
          copy:
            src: bridge
            dest: /etc/network/interfaces.d/bridge
            mode: 0644
            owner: root
            group: root
          become: true

    - name: Installing udev rules
      become: true
      get_url:
        url: "{{ clusterhat_udev_url }}"
        dest: /etc/udev/rules.d/90-clusterhat.rules
        mode: 0644
        owner: root
        group: root

    - name: Installing minicom config
      become: true
      get_url:
        url: "{{ item.value }}"
        dest: "/etc/minicom/minirc.{{ item.key }}"
        mode: 0644
        owner: root
        group: root
      with_dict: "{{ clusterhat_minicom_cfg_urls }}"

    - name: Patching cmdline for node p{{ clusterhat_node_slave_number }}
      become: true
      lineinfile:
        path: /boot/cmdline
        regexp: "^.*"
        line: '\1 init=/sbin/reconfig-clusterhat p{{ clusterhat_node_slave_number}}'
      notify: reboot
      when: clusterhat_node_type == "slave"
